/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...catchAll]': RouteRecordInfo<'/[...catchAll]', '/:catchAll(.*)', { catchAll: ParamValue<true> }, { catchAll: ParamValue<false> }>,
    '/403': RouteRecordInfo<'/403', '/403', Record<never, never>, Record<never, never>>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/attribute-values': RouteRecordInfo<'/attribute-values', '/attribute-values', Record<never, never>, Record<never, never>>,
    '/attribute-values/': RouteRecordInfo<'/attribute-values/', '/attribute-values', Record<never, never>, Record<never, never>>,
    '/attribute-values/[id]': RouteRecordInfo<'/attribute-values/[id]', '/attribute-values/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/attribute-values/create': RouteRecordInfo<'/attribute-values/create', '/attribute-values/create', Record<never, never>, Record<never, never>>,
    '/attributes': RouteRecordInfo<'/attributes', '/attributes', Record<never, never>, Record<never, never>>,
    '/attributes/': RouteRecordInfo<'/attributes/', '/attributes', Record<never, never>, Record<never, never>>,
    '/attributes/[id]': RouteRecordInfo<'/attributes/[id]', '/attributes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/attributes/create': RouteRecordInfo<'/attributes/create', '/attributes/create', Record<never, never>, Record<never, never>>,
    '/brands': RouteRecordInfo<'/brands', '/brands', Record<never, never>, Record<never, never>>,
    '/brands/': RouteRecordInfo<'/brands/', '/brands', Record<never, never>, Record<never, never>>,
    '/brands/[id]': RouteRecordInfo<'/brands/[id]', '/brands/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/brands/create': RouteRecordInfo<'/brands/create', '/brands/create', Record<never, never>, Record<never, never>>,
    '/callback': RouteRecordInfo<'/callback', '/callback', Record<never, never>, Record<never, never>>,
    '/categories': RouteRecordInfo<'/categories', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/[id]': RouteRecordInfo<'/categories/[id]', '/categories/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/categories/create': RouteRecordInfo<'/categories/create', '/categories/create', Record<never, never>, Record<never, never>>,
    '/customers': RouteRecordInfo<'/customers', '/customers', Record<never, never>, Record<never, never>>,
    '/customers/': RouteRecordInfo<'/customers/', '/customers', Record<never, never>, Record<never, never>>,
    '/customers/[id]': RouteRecordInfo<'/customers/[id]', '/customers/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/customers/create': RouteRecordInfo<'/customers/create', '/customers/create', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/orders': RouteRecordInfo<'/orders', '/orders', Record<never, never>, Record<never, never>>,
    '/orders/': RouteRecordInfo<'/orders/', '/orders', Record<never, never>, Record<never, never>>,
    '/orders/[id]/': RouteRecordInfo<'/orders/[id]/', '/orders/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/history': RouteRecordInfo<'/orders/[id]/history', '/orders/:id/history', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process': RouteRecordInfo<'/orders/[id]/process', '/orders/:id/process', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/canceled': RouteRecordInfo<'/orders/[id]/process/canceled', '/orders/:id/process/canceled', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/completed': RouteRecordInfo<'/orders/[id]/process/completed', '/orders/:id/process/completed', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/confirmation': RouteRecordInfo<'/orders/[id]/process/confirmation', '/orders/:id/process/confirmation', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/delivered': RouteRecordInfo<'/orders/[id]/process/delivered', '/orders/:id/process/delivered', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/failure': RouteRecordInfo<'/orders/[id]/process/failure', '/orders/:id/process/failure', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/packing': RouteRecordInfo<'/orders/[id]/process/packing', '/orders/:id/process/packing', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/payment': RouteRecordInfo<'/orders/[id]/process/payment', '/orders/:id/process/payment', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/pending': RouteRecordInfo<'/orders/[id]/process/pending', '/orders/:id/process/pending', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/shipping': RouteRecordInfo<'/orders/[id]/process/shipping', '/orders/:id/process/shipping', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/[id]/process/successful': RouteRecordInfo<'/orders/[id]/process/successful', '/orders/:id/process/successful', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/orders/create': RouteRecordInfo<'/orders/create', '/orders/create', Record<never, never>, Record<never, never>>,
    '/products': RouteRecordInfo<'/products', '/products', Record<never, never>, Record<never, never>>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/create': RouteRecordInfo<'/products/create', '/products/create', Record<never, never>, Record<never, never>>,
    '/profile': RouteRecordInfo<'/profile', '/profile', Record<never, never>, Record<never, never>>,
    '/profile/edit': RouteRecordInfo<'/profile/edit', '/profile/edit', Record<never, never>, Record<never, never>>,
    '/profile/info': RouteRecordInfo<'/profile/info', '/profile/info', Record<never, never>, Record<never, never>>,
    '/profile/register': RouteRecordInfo<'/profile/register', '/profile/register', Record<never, never>, Record<never, never>>,
    '/relate-groups': RouteRecordInfo<'/relate-groups', '/relate-groups', Record<never, never>, Record<never, never>>,
    '/relate-groups/': RouteRecordInfo<'/relate-groups/', '/relate-groups', Record<never, never>, Record<never, never>>,
    '/relate-groups/[id]': RouteRecordInfo<'/relate-groups/[id]', '/relate-groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/relate-groups/create': RouteRecordInfo<'/relate-groups/create', '/relate-groups/create', Record<never, never>, Record<never, never>>,
    '/roles': RouteRecordInfo<'/roles', '/roles', Record<never, never>, Record<never, never>>,
    '/roles/': RouteRecordInfo<'/roles/', '/roles', Record<never, never>, Record<never, never>>,
    '/roles/[id]': RouteRecordInfo<'/roles/[id]', '/roles/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/roles/create': RouteRecordInfo<'/roles/create', '/roles/create', Record<never, never>, Record<never, never>>,
    '/test': RouteRecordInfo<'/test', '/test', Record<never, never>, Record<never, never>>,
    '/users': RouteRecordInfo<'/users', '/users', Record<never, never>, Record<never, never>>,
    '/users/': RouteRecordInfo<'/users/', '/users', Record<never, never>, Record<never, never>>,
    '/users/[id]/': RouteRecordInfo<'/users/[id]/', '/users/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/[id]/password': RouteRecordInfo<'/users/[id]/password', '/users/:id/password', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/users/create': RouteRecordInfo<'/users/create', '/users/create', Record<never, never>, Record<never, never>>,
  }
}
