/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/analytics': RouteRecordInfo<'/analytics', '/analytics', Record<never, never>, Record<never, never>>,
    '/attribute-values/': RouteRecordInfo<'/attribute-values/', '/attribute-values', Record<never, never>, Record<never, never>>,
    '/attribute-values/[id]': RouteRecordInfo<'/attribute-values/[id]', '/attribute-values/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/attribute-values/create': RouteRecordInfo<'/attribute-values/create', '/attribute-values/create', Record<never, never>, Record<never, never>>,
    '/attributes/': RouteRecordInfo<'/attributes/', '/attributes', Record<never, never>, Record<never, never>>,
    '/attributes/[id]': RouteRecordInfo<'/attributes/[id]', '/attributes/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/attributes/create': RouteRecordInfo<'/attributes/create', '/attributes/create', Record<never, never>, Record<never, never>>,
    '/brands/': RouteRecordInfo<'/brands/', '/brands', Record<never, never>, Record<never, never>>,
    '/brands/[id]': RouteRecordInfo<'/brands/[id]', '/brands/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/brands/create': RouteRecordInfo<'/brands/create', '/brands/create', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/categories/[id]': RouteRecordInfo<'/categories/[id]', '/categories/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/categories/create': RouteRecordInfo<'/categories/create', '/categories/create', Record<never, never>, Record<never, never>>,
    '/customer': RouteRecordInfo<'/customer', '/customer', Record<never, never>, Record<never, never>>,
    '/order': RouteRecordInfo<'/order', '/order', Record<never, never>, Record<never, never>>,
    '/products/': RouteRecordInfo<'/products/', '/products', Record<never, never>, Record<never, never>>,
    '/products/[id]': RouteRecordInfo<'/products/[id]', '/products/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/products/create': RouteRecordInfo<'/products/create', '/products/create', Record<never, never>, Record<never, never>>,
    '/relate-groups/': RouteRecordInfo<'/relate-groups/', '/relate-groups', Record<never, never>, Record<never, never>>,
    '/relate-groups/[id]': RouteRecordInfo<'/relate-groups/[id]', '/relate-groups/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/relate-groups/create': RouteRecordInfo<'/relate-groups/create', '/relate-groups/create', Record<never, never>, Record<never, never>>,
  }
}
